variable "app_name"          { type = string }
variable "environment"       { type = string }
variable "aws_region"        { type = string }
variable "vpc_id"            { type = string }
variable "private_subnet_ids"{ type = list(string) }
variable "app_sg_id"         { type = string }
variable "ecr_image_url"     { type = string }
variable "alb_target_group"  { type = string }
variable "desired_count"     { type = number }
variable "container_port"    { type = number }
